In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url1 = "https://www.topuniversities.com/university-rankings/world-university-rankings/2018"
url2 = "https://www.timeshighereducation.com/world-university-rankings/2018/world-ranking#!/page/0/length/100/sort_by/rank/sort_order/asc/cols/stats"
json1 = "https://www.topuniversities.com//sites//default//files//qs-rankings-data//357051.txt"
json2 = "https://www.timeshighereducation.com//sites//default//files//the_data_rankings//world_university_rankings_2018_limit0_369a9045a203e176392b9fb8f8c1cb2a.json"
r = requests.get(json1)
json1_text = r.json()
r = requests.get(json2)
json2_text = r.json()

In [3]:
import pandas as pd
import numpy as np
num_of_rank = 200
data1 = pd.DataFrame(data=json1_text["data"][0:200], index=list(range(num_of_rank)))
data2 = pd.DataFrame(data=json2_text["data"][0:200], index=list(range(num_of_rank)))

In [4]:
d1 = data1.copy(deep=True)
d2 = data2.copy(deep=True)
d1.drop(['cc', 'core_id', 'guide', 'logo', 'nid', 'stars'], axis=1, inplace=True)
d2.drop(['aliases', 'member_level', 'nid', 'rank_order', 'record_type', 'scores_citations_rank', 'scores_citations_rank', 'scores_industry_income_rank',
       'scores_international_outlook_rank', 'scores_overall_rank', 'scores_research_rank', 'scores_teaching_rank', 'subjects_offered', 'url'], axis=1, inplace=True)

In [5]:
from bs4 import BeautifulSoup

url_base = "https://www.topuniversities.com"
div1 = '<div class="faculty-main wrapper col-md-4">'
div2 = '<div class="students-main wrapper col-md-4">'
div3 = '<div class="int-students-main wrapper col-md-4">'
class_name = ["faculty-main wrapper col-md-4", "students-main wrapper col-md-4", "int-students-main wrapper col-md-4"]

In [6]:
d1_ = d1.copy(deep=True)
d1_ = d1_.assign(Total_Faculty=0)
d1_ = d1_.assign(International_Faculty=0)
d1_ = d1_.assign(Total_Student=0)
d1_ = d1_.assign(International_Student=0)

for i in d1_.index:
    url_ = d1_.iloc[i]['url']
    r = requests.get(url_base + url_)
    soup = BeautifulSoup(r.text, 'html.parser')
    lst = []
    for ic, c in enumerate(class_name):
        a = soup.findAll("div", { "class" : c})
        if len(a) > 0:
            for j in a[0].findAll("div", { "class" : "number" }):
                lst.append(int(''.join(ch for ch in j.get_text() if ch.isdigit())))
        if ic == 0:
            lst += [np.nan] * (2-len(lst))
        if ic == 1:
            lst += [np.nan] * (3-len(lst))
        if ic == 2:
            lst += [np.nan] * (4-len(lst))                
    d1_.loc[i, ['Total_Faculty', 'International_Faculty', 'Total_Student', 'International_Student']] = lst

In [7]:
d1_

,country,rank_display,region,score,title,url,Total_Faculty,International_Faculty,Total_Student,International_Student
0,United States,1,North America,100,Massachusetts Institute of Technology (MIT),/universities/massachusetts-institute-technolo...,2982.0,1679.0,11067.0,3717.0
1,United States,2,North America,98.7,Stanford University,/universities/stanford-university,4285.0,2042.0,15878.0,3611.0
2,United States,3,North America,98.4,Harvard University,/universities/harvard-university,4350.0,1311.0,22429.0,5266.0
3,United States,4,North America,97.7,California Institute of Technology (Caltech),/universities/california-institute-technology-...,953.0,350.0,2255.0,647.0
4,United Kingdom,5,Europe,95.6,University of Cambridge,/universities/university-cambridge,5490.0,2278.0,18770.0,6699.0
5,United Kingdom,6,Europe,95.3,University of Oxford,/universities/university-oxford,6750.0,2964.0,19720.0,7353.0
6,United Kingdom,7,Europe,94.6,UCL (University College London),/universities/ucl-university-college-london,6345.0,2554.0,31080.0,14854.0
7,United Kingdom,8,Europe,93.7,Imperial College London,/universities/imperial-college-london,3930.0,2071.0,16090.0,8746.0
8,United States,9,North America,93.5,University of Chicago,/universities/university-chicago,2449.0,635.0,13557.0,3379.0
9,Switzerland,10,Europe,93.3,ETH Zurich - Swiss Federal Institute of Techno...,/universities/eth-zurich-swiss-federal-institu...,2477.0,1886.0,19815.0,7563.0
10,Singapore,11,Asia,92.2,"Nanyang Technological University, Singapore (NTU)",/universities/nanyang-technological-university...,4338.0,2993.0,25738.0,7251.0
11,Switzerland,12,Europe,91.2,Ecole Polytechnique Fédérale de Lausanne (EPFL),/universities/ecole-polytechnique-f%C3%A9d%C3%...,1695.0,1300.0,10343.0,5896.0
12,United States,13,North America,91,Princeton University,/universities/princeton-university,1007.0,246.0,8069.0,1793.0
13,United States,14,North America,90.7,Cornell University,/universities/cornell-university,2718.0,970.0,21904.0,5411.0
14,Singapore,15,Asia,90.5,National University of Singapore (NUS),/universities/national-university-singapore-nus,5106.0,3086.0,32728.0,8917.0
15,United States,16,North America,90.4,Yale University,/universities/yale-university,4940.0,1708.0,12402.0,2469.0
16,United States,17,North America,89.8,Johns Hopkins University,/universities/johns-hopkins-university,4462.0,1061.0,16146.0,4105.0
17,United States,18,North America,88.9,Columbia University,/universities/columbia-university,6189.0,913.0,25045.0,8105.0
18,United States,19,North America,88.7,University of Pennsylvania,/universities/university-pennsylvania,5499.0,1383.0,20639.0,4250.0
19,Australia,20,Oceania,87.1,The Australian National University,/universities/australian-national-university,1600.0,927.0,14442.0,5551.0
20,United States,=21,North America,87,University of Michigan,/universities/university-michigan,6809.0,1920.0,43147.0,7527.0
21,United States,=21,North America,87,Duke University,/universities/duke-university,2938.0,226.0,15320.0,2864.0
22,United Kingdom,=23,Europe,86.9,The University of Edinburgh,/universities/university-edinburgh,4075.0,1553.0,28040.0,10551.0
23,United Kingdom,=23,Europe,86.9,King's College London,/universities/kings-college-london,3650.0,1513.0,23780.0,9451.0
24,China,25,Asia,85.6,Tsinghua University,/universities/tsinghua-university,5506.0,932.0,36300.0,4072.0
25,Hong Kong,26,Asia,85.5,The University of Hong Kong,/universities/university-hong-kong,3012.0,2085.0,20214.0,8230.0
26,United States,27,North America,84.9,"University of California, Berkeley (UCB)",/universities/university-california-berkeley-ucb,3321.0,1395.0,36703.0,6086.0
27,Japan,=28,Asia,84.8,The University of Tokyo,/universities/university-tokyo,4514.0,254.0,27279.0,2639.0
28,United States,=28,North America,84.8,Northwestern University,/universities/northwestern-university,4231.0,1141.0,18675.0,3422.0
29,Hong Kong,30,Asia,84.3,The Hong Kong University of Science and Techno...,/universities/hong-kong-university-science-tec...,1150.0,835.0,10375.0,2921.0
...,...,...,...,...,...,...,...,...,...,...
170,Germany,171,Europe,50.8,Albert-Ludwigs-Universitaet Freiburg,/universities/albert-ludwigs-universitaet-frei...,1966.0,413.0,23214.0,3897.0
171,India,172,Asia,50.7,Indian Institute of Technology Delhi (IITD),/universities/indian-institute-technology-delh...,466.0,4.0,7477.0,80.0
172,Saudi Arabia,=173,Asia,50.3,King Fahd University of Petroleum & Minerals,/universities/king-fahd-university-petroleum-m...,1062.0,665.0,6040.0,989.0
173,United Kingdom,=173,Europe,50.3,University of Liverpool,/universities/university-liverpool,2390.0,717.0,22065.0,7502.0
174,United States,=173,North America,50.3,University of Virginia,/universities/university-virginia,2509.0,487.0,21560.0,1899.0
175,Australia,176,Oceania,50.1,University of Technology Sydney,/universities/university-technology-sydney,1328.0,546.0,24207.0,7769.0
176,France,177,Europe,50,CentraleSupélec,/universities/centralesup%C3%A9lec,529.0,137.0,3877.0,1132.0
177,United States,178,North America,49.8,University of Florida,/universities/university-florida,5419.0,504.0,45485.0,4597.0
178,India,=179,Asia,49.7,Indian Institute of Technology Bombay (IITB),/universities/indian-institute-technology-bomb...,876.0,19.0,9402.0,93.0
179,Netherlands,=179,Europe,49.7,University of Twente,/universities/university-twente,910.0,299.0,9332.0,2235.0
180,Germany,181,Europe,49.6,University of Göttingen,/universities/university-g%C3%B6ttingen,3678.0,641.0,30402.0,3736.0
181,Belgium,=182,Europe,49.5,Vrije Universiteit Brussel (VUB),/universities/vrije-universiteit-brussel-vub,1792.0,515.0,9284.0,1853.0
182,Brazil,=182,Latin America,49.5,Universidade Estadual de Campinas (Unicamp),/universities/universidade-estadual-de-campina...,1968.0,109.0,26572.0,966.0
183,United States,=182,North America,49.5,University of Colorado Boulder,/universities/university-colorado-boulder,3685.0,566.0,30219.0,2679.0
184,Austria,=182,Europe,49.5,Vienna University of Technology,/universities/vienna-university-technology,706.0,172.0,17479.0,5199.0
185,United States,186,North America,49.3,University of Rochester,/universities/university-rochester,2569.0,488.0,9636.0,2805.0
186,Spain,187,Europe,49.2,Universidad Autónoma de Madrid,/universities/universidad-aut%C3%B3noma-de-madrid,2738.0,181.0,26511.0,2976.0
187,Italy,=188,Europe,49.1,Alma Mater Studiorum - University of Bologna,/universities/alma-mater-studiorum-university-...,2990.0,153.0,63399.0,4195.0
188,United Kingdom,=188,Europe,49.1,University of Reading,/universities/university-reading,1280.0,422.0,13330.0,4077.0
189,India,190,Asia,49,Indian Institute of Science (IISc) Bangalore,/universities/indian-institute-science-iisc-ba...,423.0,NaN,4071.0,47.0
190,South Africa,191,Africa,48.9,University of Cape Town,/universities/university-cape-town,1733.0,379.0,19593.0,3325.0
191,Italy,=192,Europe,48.5,Scuola Normale Superiore di Pisa,/universities/scuola-normale-superiore-di-pisa,86.0,1.0,532.0,48.0
192,Italy,=192,Europe,48.5,Scuola Superiore Sant'Anna Pisa di Studi Unive...,/universities/scuola-superiore-santanna-pisa-d...,119.0,1.0,789.0,135.0
193,Japan,=192,Asia,48.5,Keio University CEMS MIM,/universities/keio-university-cems-mim,3905.0,261.0,33500.0,2178.0
194,Sweden,=195,Europe,48.1,Stockholm University,/universities/stockholm-university,2154.0,646.0,28281.0,2636.0
195,Spain,=195,Europe,48.1,Universitat Autònoma de Barcelona,/universities/universitat-aut%C3%B2noma-de-bar...,2187.0,230.0,31986.0,3848.0
196,United States,=195,North America,48.1,Texas A&M University,/universities/texas-am-university,3446.0,206.0,60294.0,4900.0
197,Mexico,199,Latin America,48,Instituto Tecnológico y de Estudios Superiores...,/universities/instituto-tecnol%C3%B3gico-y-de-...,1822.0,821.0,13376.0,1412.0
198,Netherlands,200,Europe,47.9,Maastricht University,/universities/maastricht-university,1277.0,502.0,16385.0,8234.0
199,Chile,201,Latin America,47.8,Universidad de Chile,/universities/universidad-de-chile,2256.0,127.0,38848.0,2134.0

In [8]:
d2

,location,name,rank,scores_citations,scores_industry_income,scores_international_outlook,scores_overall,scores_research,scores_teaching,stats_female_male_ratio,stats_number_students,stats_pc_intl_students,stats_student_staff_ratio
0,United Kingdom,University of Oxford,1,99.1,63.7,95.0,94.3,99.5,86.7,46 : 54,"20,409",38%,11.2
1,United Kingdom,University of Cambridge,2,97.5,51.5,93.0,93.2,97.8,87.8,45 : 55,"18,389",35%,10.9
2,United States,California Institute of Technology,=3,99.5,92.6,59.7,93.0,97.5,90.3,31 : 69,"2,209",27%,6.5
3,United States,Stanford University,=3,99.9,60.5,77.6,93.0,96.7,89.1,42 : 58,"15,845",22%,7.5
4,United States,Massachusetts Institute of Technology,5,100.0,88.4,87.6,92.5,91.9,87.3,37 : 63,"11,177",34%,8.7
5,United States,Harvard University,6,99.7,46.4,79.7,91.8,98.4,84.2,None,"20,326",26%,8.9
6,United States,Princeton University,7,99.6,58.0,78.7,91.1,93.9,85.7,45 : 55,"7,955",24%,8.3
7,United Kingdom,Imperial College London,8,96.7,71.6,96.6,89.2,88.7,81.7,37 : 63,"15,857",55%,11.4
8,United States,University of Chicago,9,99.4,39.8,69.6,88.6,90.1,85.3,44 : 56,"13,525",25%,6.2
9,Switzerland,ETH Zurich – Swiss Federal Institute of Techno...,=10,94.3,60.3,98.1,87.7,92.0,76.4,31 : 69,"19,233",38%,14.6
10,United States,University of Pennsylvania,=10,98.5,56.9,61.3,87.7,90.1,83.7,50 : 50,"20,361",20%,6.5
11,United States,Yale University,12,98.4,45.1,64.6,87.6,87.0,86.7,49 : 51,"12,155",21%,4.3
12,United States,Johns Hopkins University,13,98.4,95.8,70.6,86.5,88.1,76.1,52 : 48,"15,498",24%,4.3
13,United States,Columbia University,14,98.8,41.3,76.6,86.0,83.3,82.2,None,"26,587",32%,6.1
14,United States,"University of California, Los Angeles",15,97.9,48.6,59.5,85.7,88.1,80.7,53 : 47,"39,279",17%,9.6
15,United Kingdom,University College London,16,94.6,41.2,94.6,85.3,88.2,74.4,56 : 44,"30,304",49%,10.5
16,United States,Duke University,17,98.3,100.0,62.5,85.1,80.6,80.7,49 : 51,"15,256",22%,4.5
17,United States,"University of California, Berkeley",18,99.8,37.5,64.5,84.3,84.5,77.4,52 : 48,"36,182",17%,13.1
18,United States,Cornell University,19,97.6,34.6,69.2,84.2,86.6,76.2,49 : 51,"21,850",24%,9.8
19,United States,Northwestern University,20,96.9,78.2,59.2,83.3,86.7,72.6,48 : 52,"17,466",18%,12.8
20,United States,University of Michigan,21,95.7,46.2,55.8,83.1,86.3,77.2,48 : 52,"41,818",16%,8.6
21,Singapore,National University of Singapore,=22,81.3,61.9,95.8,82.8,88.2,77.4,51 : 49,"30,602",30%,17.0
22,Canada,University of Toronto,=22,92.6,46.5,80.1,82.8,84.8,74.6,None,"69,427",17%,18.7
23,United States,Carnegie Mellon University,24,99.7,50.4,79.1,81.9,83.7,65.8,39 : 61,"12,676",45%,13.5
24,United Kingdom,London School of Economics and Political Science,=25,94.9,33.7,92.2,79.4,72.0,71.8,52 : 48,"10,065",71%,12.2
25,United States,University of Washington,=25,99.0,47.3,56.5,79.4,79.9,67.9,52 : 48,"44,945",16%,11.4
26,United Kingdom,University of Edinburgh,=27,97.0,36.3,92.0,79.2,74.2,66.8,59 : 41,"26,759",40%,12.5
27,United States,New York University,=27,96.5,37.0,53.4,79.2,77.4,73.7,56 : 44,"43,860",26%,9.6
28,China,Peking University,=27,74.2,100.0,53.0,79.2,85.1,83.0,47 : 53,"42,136",16%,8.9
29,China,Tsinghua University,30,71.4,99.8,41.0,79.0,93.2,80.2,32 : 68,"42,089",9%,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,South Africa,University of Cape Town,171,87.0,88.5,81.1,54.4,36.2,30.5,53 : 47,"20,775",18%,11.7
171,United States,"Rutgers, the State University of New Jersey",172,79.7,36.9,39.2,54.3,45.3,43.0,52 : 48,"43,439",10%,11.1
172,Sweden,KTH Royal Institute of Technology,=173,67.0,50.9,83.7,54.2,46.3,42.3,33 : 67,"12,951",17%,16.0
173,Germany,University of Münster,=173,81.2,60.8,47.7,54.2,42.1,40.3,53 : 47,"42,287",7%,42.6
174,Belgium,Université Libre de Bruxelles,=175,80.4,48.4,83.2,54.0,42.2,32.4,55 : 45,"25,343",35%,43.4
175,United Kingdom,Newcastle University,=175,80.6,41.6,86.7,54.0,40.8,33.4,49 : 51,"20,952",30%,15.6
176,United Kingdom,University of Liverpool,=177,86.8,37.1,89.9,53.9,34.7,32.7,54 : 46,"19,815",35%,11.7
177,China,Zhejiang University,=177,45.1,89.4,25.2,53.9,63.7,57.0,22 : 78,"50,051",6%,14.1
178,Luxembourg,University of Luxembourg,=179,91.9,39.6,99.8,53.8,32.4,26.8,50 : 50,"4,969",57%,14.6
179,Netherlands,University of Twente,=179,68.5,83.6,85.3,53.8,47.0,35.5,37 : 63,"6,697",27%,12.8
180,France,Paris-Sud University,181,86.8,32.3,63.5,53.7,33.1,40.4,55 : 45,"27,221",16%,14.5
181,France,École Normale Supérieure de Lyon,=182,80.9,37.9,67.3,53.6,37.8,40.1,47 : 53,"2,221",13%,8.5
182,Hong Kong,Hong Kong Polytechnic University,=182,67.7,45.8,79.9,53.6,48.1,39.1,51 : 49,"21,773",25%,26.9
183,Italy,Scuola Normale Superiore di Pisa,184,75.4,37.7,49.4,53.4,33.3,53.7,30 : 70,515,7%,5.2
184,United Kingdom,University of Aberdeen,185,87.1,41.9,93.3,53.3,33.6,30.3,55 : 45,"12,055",36%,13.9
185,United States,University of Miami,186,90.3,37.2,67.1,53.1,24.4,42.5,51 : 49,"15,860",16%,5.9
186,United Kingdom,University of Dundee,187,94.5,43.4,79.8,52.9,32.0,26.3,62 : 38,"10,893",24%,14.9
187,United Kingdom,University of East Anglia,=188,90.5,32.2,85.6,52.8,31.6,29.9,60 : 40,"13,521",30%,13.6
188,China,Shanghai Jiao Tong University,=188,44.1,88.9,33.4,52.8,62.5,53.5,41 : 59,"37,288",6%,12.4
189,Finland,Aalto University,190,79.5,52.5,72.5,52.7,35.8,37.8,34 : 66,"12,744",20%,20.2
190,United States,University of Massachusetts,191,88.8,51.0,54.8,52.6,32.2,36.3,49 : 51,"59,230",14%,13.3
191,New Zealand,University of Auckland,192,73.8,67.3,90.6,52.5,40.7,32.5,54 : 46,"30,348",29%,18.8
192,United States,Northeastern University,193,91.7,35.4,70.1,52.4,26.8,35.6,49 : 51,"18,780",32%,14.0
193,Russian Federation,Lomonosov Moscow State University,194,15.8,89.0,61.1,52.3,61.6,74.2,48 : 52,"29,236",22%,7.3
194,Netherlands,Tilburg University,195,61.3,59.0,75.8,52.1,50.1,38.4,48 : 52,"7,738",13%,22.5
195,France,Paris-Sorbonne University – Paris 4,196,77.1,32.1,57.9,52.0,34.3,44.6,68 : 32,"22,042",15%,30.2
196,United Kingdom,"Royal Holloway, University of London",197,85.0,35.0,93.0,51.9,27.9,33.9,59 : 41,"8,931",40%,15.4
197,United States,"University of California, Riverside",=198,92.3,37.4,63.9,51.7,30.9,30.0,51 : 49,"20,740",14%,20.7
198,Sweden,University of Gothenburg,=198,87.5,38.9,62.5,51.7,39.2,26.7,None,"18,378",13%,10.0
199,Taiwan,National Taiwan University,=198,53.4,65.0,33.4,51.7,54.7,50.4,40 : 60,"31,758",8%,11.5

In [9]:
data1 = d1_.copy()
data2 = d2.copy()

In [10]:
data2

,location,name,rank,scores_citations,scores_industry_income,scores_international_outlook,scores_overall,scores_research,scores_teaching,stats_female_male_ratio,stats_number_students,stats_pc_intl_students,stats_student_staff_ratio
0,United Kingdom,University of Oxford,1,99.1,63.7,95.0,94.3,99.5,86.7,46 : 54,"20,409",38%,11.2
1,United Kingdom,University of Cambridge,2,97.5,51.5,93.0,93.2,97.8,87.8,45 : 55,"18,389",35%,10.9
2,United States,California Institute of Technology,=3,99.5,92.6,59.7,93.0,97.5,90.3,31 : 69,"2,209",27%,6.5
3,United States,Stanford University,=3,99.9,60.5,77.6,93.0,96.7,89.1,42 : 58,"15,845",22%,7.5
4,United States,Massachusetts Institute of Technology,5,100.0,88.4,87.6,92.5,91.9,87.3,37 : 63,"11,177",34%,8.7
5,United States,Harvard University,6,99.7,46.4,79.7,91.8,98.4,84.2,None,"20,326",26%,8.9
6,United States,Princeton University,7,99.6,58.0,78.7,91.1,93.9,85.7,45 : 55,"7,955",24%,8.3
7,United Kingdom,Imperial College London,8,96.7,71.6,96.6,89.2,88.7,81.7,37 : 63,"15,857",55%,11.4
8,United States,University of Chicago,9,99.4,39.8,69.6,88.6,90.1,85.3,44 : 56,"13,525",25%,6.2
9,Switzerland,ETH Zurich – Swiss Federal Institute of Techno...,=10,94.3,60.3,98.1,87.7,92.0,76.4,31 : 69,"19,233",38%,14.6
10,United States,University of Pennsylvania,=10,98.5,56.9,61.3,87.7,90.1,83.7,50 : 50,"20,361",20%,6.5
11,United States,Yale University,12,98.4,45.1,64.6,87.6,87.0,86.7,49 : 51,"12,155",21%,4.3
12,United States,Johns Hopkins University,13,98.4,95.8,70.6,86.5,88.1,76.1,52 : 48,"15,498",24%,4.3
13,United States,Columbia University,14,98.8,41.3,76.6,86.0,83.3,82.2,None,"26,587",32%,6.1
14,United States,"University of California, Los Angeles",15,97.9,48.6,59.5,85.7,88.1,80.7,53 : 47,"39,279",17%,9.6
15,United Kingdom,University College London,16,94.6,41.2,94.6,85.3,88.2,74.4,56 : 44,"30,304",49%,10.5
16,United States,Duke University,17,98.3,100.0,62.5,85.1,80.6,80.7,49 : 51,"15,256",22%,4.5
17,United States,"University of California, Berkeley",18,99.8,37.5,64.5,84.3,84.5,77.4,52 : 48,"36,182",17%,13.1
18,United States,Cornell University,19,97.6,34.6,69.2,84.2,86.6,76.2,49 : 51,"21,850",24%,9.8
19,United States,Northwestern University,20,96.9,78.2,59.2,83.3,86.7,72.6,48 : 52,"17,466",18%,12.8
20,United States,University of Michigan,21,95.7,46.2,55.8,83.1,86.3,77.2,48 : 52,"41,818",16%,8.6
21,Singapore,National University of Singapore,=22,81.3,61.9,95.8,82.8,88.2,77.4,51 : 49,"30,602",30%,17.0
22,Canada,University of Toronto,=22,92.6,46.5,80.1,82.8,84.8,74.6,None,"69,427",17%,18.7
23,United States,Carnegie Mellon University,24,99.7,50.4,79.1,81.9,83.7,65.8,39 : 61,"12,676",45%,13.5
24,United Kingdom,London School of Economics and Political Science,=25,94.9,33.7,92.2,79.4,72.0,71.8,52 : 48,"10,065",71%,12.2
25,United States,University of Washington,=25,99.0,47.3,56.5,79.4,79.9,67.9,52 : 48,"44,945",16%,11.4
26,United Kingdom,University of Edinburgh,=27,97.0,36.3,92.0,79.2,74.2,66.8,59 : 41,"26,759",40%,12.5
27,United States,New York University,=27,96.5,37.0,53.4,79.2,77.4,73.7,56 : 44,"43,860",26%,9.6
28,China,Peking University,=27,74.2,100.0,53.0,79.2,85.1,83.0,47 : 53,"42,136",16%,8.9
29,China,Tsinghua University,30,71.4,99.8,41.0,79.0,93.2,80.2,32 : 68,"42,089",9%,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,South Africa,University of Cape Town,171,87.0,88.5,81.1,54.4,36.2,30.5,53 : 47,"20,775",18%,11.7
171,United States,"Rutgers, the State University of New Jersey",172,79.7,36.9,39.2,54.3,45.3,43.0,52 : 48,"43,439",10%,11.1
172,Sweden,KTH Royal Institute of Technology,=173,67.0,50.9,83.7,54.2,46.3,42.3,33 : 67,"12,951",17%,16.0
173,Germany,University of Münster,=173,81.2,60.8,47.7,54.2,42.1,40.3,53 : 47,"42,287",7%,42.6
174,Belgium,Université Libre de Bruxelles,=175,80.4,48.4,83.2,54.0,42.2,32.4,55 : 45,"25,343",35%,43.4
175,United Kingdom,Newcastle University,=175,80.6,41.6,86.7,54.0,40.8,33.4,49 : 51,"20,952",30%,15.6
176,United Kingdom,University of Liverpool,=177,86.8,37.1,89.9,53.9,34.7,32.7,54 : 46,"19,815",35%,11.7
177,China,Zhejiang University,=177,45.1,89.4,25.2,53.9,63.7,57.0,22 : 78,"50,051",6%,14.1
178,Luxembourg,University of Luxembourg,=179,91.9,39.6,99.8,53.8,32.4,26.8,50 : 50,"4,969",57%,14.6
179,Netherlands,University of Twente,=179,68.5,83.6,85.3,53.8,47.0,35.5,37 : 63,"6,697",27%,12.8
180,France,Paris-Sud University,181,86.8,32.3,63.5,53.7,33.1,40.4,55 : 45,"27,221",16%,14.5
181,France,École Normale Supérieure de Lyon,=182,80.9,37.9,67.3,53.6,37.8,40.1,47 : 53,"2,221",13%,8.5
182,Hong Kong,Hong Kong Polytechnic University,=182,67.7,45.8,79.9,53.6,48.1,39.1,51 : 49,"21,773",25%,26.9
183,Italy,Scuola Normale Superiore di Pisa,184,75.4,37.7,49.4,53.4,33.3,53.7,30 : 70,515,7%,5.2
184,United Kingdom,University of Aberdeen,185,87.1,41.9,93.3,53.3,33.6,30.3,55 : 45,"12,055",36%,13.9
185,United States,University of Miami,186,90.3,37.2,67.1,53.1,24.4,42.5,51 : 49,"15,860",16%,5.9
186,United Kingdom,University of Dundee,187,94.5,43.4,79.8,52.9,32.0,26.3,62 : 38,"10,893",24%,14.9
187,United Kingdom,University of East Anglia,=188,90.5,32.2,85.6,52.8,31.6,29.9,60 : 40,"13,521",30%,13.6
188,China,Shanghai Jiao Tong University,=188,44.1,88.9,33.4,52.8,62.5,53.5,41 : 59,"37,288",6%,12.4
189,Finland,Aalto University,190,79.5,52.5,72.5,52.7,35.8,37.8,34 : 66,"12,744",20%,20.2
190,United States,University of Massachusetts,191,88.8,51.0,54.8,52.6,32.2,36.3,49 : 51,"59,230",14%,13.3
191,New Zealand,University of Auckland,192,73.8,67.3,90.6,52.5,40.7,32.5,54 : 46,"30,348",29%,18.8
192,United States,Northeastern University,193,91.7,35.4,70.1,52.4,26.8,35.6,49 : 51,"18,780",32%,14.0
193,Russian Federation,Lomonosov Moscow State University,194,15.8,89.0,61.1,52.3,61.6,74.2,48 : 52,"29,236",22%,7.3
194,Netherlands,Tilburg University,195,61.3,59.0,75.8,52.1,50.1,38.4,48 : 52,"7,738",13%,22.5
195,France,Paris-Sorbonne University – Paris 4,196,77.1,32.1,57.9,52.0,34.3,44.6,68 : 32,"22,042",15%,30.2
196,United Kingdom,"Royal Holloway, University of London",197,85.0,35.0,93.0,51.9,27.9,33.9,59 : 41,"8,931",40%,15.4
197,United States,"University of California, Riverside",=198,92.3,37.4,63.9,51.7,30.9,30.0,51 : 49,"20,740",14%,20.7
198,Sweden,University of Gothenburg,=198,87.5,38.9,62.5,51.7,39.2,26.7,None,"18,378",13%,10.0
199,Taiwan,National Taiwan University,=198,53.4,65.0,33.4,51.7,54.7,50.4,40 : 60,"31,758",8%,11.5

In [11]:
data1

,country,rank_display,region,score,title,url,Total_Faculty,International_Faculty,Total_Student,International_Student
0,United States,1,North America,100,Massachusetts Institute of Technology (MIT),/universities/massachusetts-institute-technolo...,2982.0,1679.0,11067.0,3717.0
1,United States,2,North America,98.7,Stanford University,/universities/stanford-university,4285.0,2042.0,15878.0,3611.0
2,United States,3,North America,98.4,Harvard University,/universities/harvard-university,4350.0,1311.0,22429.0,5266.0
3,United States,4,North America,97.7,California Institute of Technology (Caltech),/universities/california-institute-technology-...,953.0,350.0,2255.0,647.0
4,United Kingdom,5,Europe,95.6,University of Cambridge,/universities/university-cambridge,5490.0,2278.0,18770.0,6699.0
5,United Kingdom,6,Europe,95.3,University of Oxford,/universities/university-oxford,6750.0,2964.0,19720.0,7353.0
6,United Kingdom,7,Europe,94.6,UCL (University College London),/universities/ucl-university-college-london,6345.0,2554.0,31080.0,14854.0
7,United Kingdom,8,Europe,93.7,Imperial College London,/universities/imperial-college-london,3930.0,2071.0,16090.0,8746.0
8,United States,9,North America,93.5,University of Chicago,/universities/university-chicago,2449.0,635.0,13557.0,3379.0
9,Switzerland,10,Europe,93.3,ETH Zurich - Swiss Federal Institute of Techno...,/universities/eth-zurich-swiss-federal-institu...,2477.0,1886.0,19815.0,7563.0
10,Singapore,11,Asia,92.2,"Nanyang Technological University, Singapore (NTU)",/universities/nanyang-technological-university...,4338.0,2993.0,25738.0,7251.0
11,Switzerland,12,Europe,91.2,Ecole Polytechnique Fédérale de Lausanne (EPFL),/universities/ecole-polytechnique-f%C3%A9d%C3%...,1695.0,1300.0,10343.0,5896.0
12,United States,13,North America,91,Princeton University,/universities/princeton-university,1007.0,246.0,8069.0,1793.0
13,United States,14,North America,90.7,Cornell University,/universities/cornell-university,2718.0,970.0,21904.0,5411.0
14,Singapore,15,Asia,90.5,National University of Singapore (NUS),/universities/national-university-singapore-nus,5106.0,3086.0,32728.0,8917.0
15,United States,16,North America,90.4,Yale University,/universities/yale-university,4940.0,1708.0,12402.0,2469.0
16,United States,17,North America,89.8,Johns Hopkins University,/universities/johns-hopkins-university,4462.0,1061.0,16146.0,4105.0
17,United States,18,North America,88.9,Columbia University,/universities/columbia-university,6189.0,913.0,25045.0,8105.0
18,United States,19,North America,88.7,University of Pennsylvania,/universities/university-pennsylvania,5499.0,1383.0,20639.0,4250.0
19,Australia,20,Oceania,87.1,The Australian National University,/universities/australian-national-university,1600.0,927.0,14442.0,5551.0
20,United States,=21,North America,87,University of Michigan,/universities/university-michigan,6809.0,1920.0,43147.0,7527.0
21,United States,=21,North America,87,Duke University,/universities/duke-university,2938.0,226.0,15320.0,2864.0
22,United Kingdom,=23,Europe,86.9,The University of Edinburgh,/universities/university-edinburgh,4075.0,1553.0,28040.0,10551.0
23,United Kingdom,=23,Europe,86.9,King's College London,/universities/kings-college-london,3650.0,1513.0,23780.0,9451.0
24,China,25,Asia,85.6,Tsinghua University,/universities/tsinghua-university,5506.0,932.0,36300.0,4072.0
25,Hong Kong,26,Asia,85.5,The University of Hong Kong,/universities/university-hong-kong,3012.0,2085.0,20214.0,8230.0
26,United States,27,North America,84.9,"University of California, Berkeley (UCB)",/universities/university-california-berkeley-ucb,3321.0,1395.0,36703.0,6086.0
27,Japan,=28,Asia,84.8,The University of Tokyo,/universities/university-tokyo,4514.0,254.0,27279.0,2639.0
28,United States,=28,North America,84.8,Northwestern University,/universities/northwestern-university,4231.0,1141.0,18675.0,3422.0
29,Hong Kong,30,Asia,84.3,The Hong Kong University of Science and Techno...,/universities/hong-kong-university-science-tec...,1150.0,835.0,10375.0,2921.0
...,...,...,...,...,...,...,...,...,...,...
170,Germany,171,Europe,50.8,Albert-Ludwigs-Universitaet Freiburg,/universities/albert-ludwigs-universitaet-frei...,1966.0,413.0,23214.0,3897.0
171,India,172,Asia,50.7,Indian Institute of Technology Delhi (IITD),/universities/indian-institute-technology-delh...,466.0,4.0,7477.0,80.0
172,Saudi Arabia,=173,Asia,50.3,King Fahd University of Petroleum & Minerals,/universities/king-fahd-university-petroleum-m...,1062.0,665.0,6040.0,989.0
173,United Kingdom,=173,Europe,50.3,University of Liverpool,/universities/university-liverpool,2390.0,717.0,22065.0,7502.0
174,United States,=173,North America,50.3,University of Virginia,/universities/university-virginia,2509.0,487.0,21560.0,1899.0
175,Australia,176,Oceania,50.1,University of Technology Sydney,/universities/university-technology-sydney,1328.0,546.0,24207.0,7769.0
176,France,177,Europe,50,CentraleSupélec,/universities/centralesup%C3%A9lec,529.0,137.0,3877.0,1132.0
177,United States,178,North America,49.8,University of Florida,/universities/university-florida,5419.0,504.0,45485.0,4597.0
178,India,=179,Asia,49.7,Indian Institute of Technology Bombay (IITB),/universities/indian-institute-technology-bomb...,876.0,19.0,9402.0,93.0
179,Netherlands,=179,Europe,49.7,University of Twente,/universities/university-twente,910.0,299.0,9332.0,2235.0
180,Germany,181,Europe,49.6,University of Göttingen,/universities/university-g%C3%B6ttingen,3678.0,641.0,30402.0,3736.0
181,Belgium,=182,Europe,49.5,Vrije Universiteit Brussel (VUB),/universities/vrije-universiteit-brussel-vub,1792.0,515.0,9284.0,1853.0
182,Brazil,=182,Latin America,49.5,Universidade Estadual de Campinas (Unicamp),/universities/universidade-estadual-de-campina...,1968.0,109.0,26572.0,966.0
183,United States,=182,North America,49.5,University of Colorado Boulder,/universities/university-colorado-boulder,3685.0,566.0,30219.0,2679.0
184,Austria,=182,Europe,49.5,Vienna University of Technology,/universities/vienna-university-technology,706.0,172.0,17479.0,5199.0
185,United States,186,North America,49.3,University of Rochester,/universities/university-rochester,2569.0,488.0,9636.0,2805.0
186,Spain,187,Europe,49.2,Universidad Autónoma de Madrid,/universities/universidad-aut%C3%B3noma-de-madrid,2738.0,181.0,26511.0,2976.0
187,Italy,=188,Europe,49.1,Alma Mater Studiorum - University of Bologna,/universities/alma-mater-studiorum-university-...,2990.0,153.0,63399.0,4195.0
188,United Kingdom,=188,Europe,49.1,University of Reading,/universities/university-reading,1280.0,422.0,13330.0,4077.0
189,India,190,Asia,49,Indian Institute of Science (IISc) Bangalore,/universities/indian-institute-science-iisc-ba...,423.0,NaN,4071.0,47.0
190,South Africa,191,Africa,48.9,University of Cape Town,/universities/university-cape-town,1733.0,379.0,19593.0,3325.0
191,Italy,=192,Europe,48.5,Scuola Normale Superiore di Pisa,/universities/scuola-normale-superiore-di-pisa,86.0,1.0,532.0,48.0
192,Italy,=192,Europe,48.5,Scuola Superiore Sant'Anna Pisa di Studi Unive...,/universities/scuola-superiore-santanna-pisa-d...,119.0,1.0,789.0,135.0
193,Japan,=192,Asia,48.5,Keio University CEMS MIM,/universities/keio-university-cems-mim,3905.0,261.0,33500.0,2178.0
194,Sweden,=195,Europe,48.1,Stockholm University,/universities/stockholm-university,2154.0,646.0,28281.0,2636.0
195,Spain,=195,Europe,48.1,Universitat Autònoma de Barcelona,/universities/universitat-aut%C3%B2noma-de-bar...,2187.0,230.0,31986.0,3848.0
196,United States,=195,North America,48.1,Texas A&M University,/universities/texas-am-university,3446.0,206.0,60294.0,4900.0
197,Mexico,199,Latin America,48,Instituto Tecnológico y de Estudios Superiores...,/universities/instituto-tecnol%C3%B3gico-y-de-...,1822.0,821.0,13376.0,1412.0
198,Netherlands,200,Europe,47.9,Maastricht University,/universities/maastricht-university,1277.0,502.0,16385.0,8234.0
199,Chile,201,Latin America,47.8,Universidad de Chile,/universities/universidad-de-chile,2256.0,127.0,38848.0,2134.0